name: Mend CLI Release Scan

on:
  workflow_dispatch

jobs:
  mendscan:
    env:
    #SCA
    MEND_EMAIL: ${{secrets.MEND_SCA_EMAIL}}
    MEND_USER_KEY: ${{secrets.MEND_SCA_USERKEY}}
    MEND_URL: "https://saas-eu.mend.io"
    #SAST
    MEND_SAST_SERVER_URL: "https://saas-eu.mend.io/sast"
    MEND_SAST_API_TOKEN: ${{secrets.MEND_SAST_API}}
    MEND_SAST_ORGANIZATION: ${{secrets.MEND_SAST_ORGANIZATION}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Add your package manager build here
    # name: Build with NPM
    # run: npm install

    - name: Mend CLI Scan
      run: |
        echo Downloading Mend CLI
        curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
        echo Start Mend CLI scan
        ./mend sca
        ./mend sast
